version: '3.8'

services:
  web:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8082
    volumes:
      - .:/usr/src/app/
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workdb

volumes:
  postgres_data: